### ISSUE TITLE
cannot find module dreamerV2

### ISSUE THREAD

**Issue by ahmed-kar** [RajGhugare19/dreamerv2#5]
Hi, When I download the dependencies however in your eval.py it says from dreamerv2.utils.wrapper, it says dreamerv2 module not found. Why do I need to pip install dreamerv2 when this repo is meant to me an implementation of Dreamerv2 in pytorch. 
Am I missing something.
Thanks for the great repo though, really handy.

**Comment by jdubkim** [comment]
Run pip install -e .  in dreamerv2 directory. This should solve the problem.

**Comment by ahmed-kar** [comment]
Thank you so much for this
